GET http://localhost:8080/pokemons
###
GET http://localhost:8080/pokemons/5
###
GET http://localhost:8080/pokemons/type/All

###

GET http://localhost:8080/pokemons/random

###

GET http://localhost:8080/pokemons/name/Bulbasaur

###

GET http://localhost:8080/pokemons/race/5