GET http://localhost:8080/pokemons
###
GET http://localhost:8080/pokemons/onePokemon/5
###
GET http://localhost:8080/pokemons/type/Grass

###

GET http://localhost:8080/pokemons/random

###

GET http://localhost:8080/pokemons/name/asasfasd

###

GET http://localhost:8080/pokemons/race/5